all:
	cp /home/felix/ss12/bibtex/Master_Thesis.bib /home/felix/ss12/master_thesis/icra-paper/bibtex
	pdflatex icra-paper
	bibtex icra-paper
	pdflatex icra-paper
	pdflatex icra-paper
short:
	pdflatex icra-paper
	pdflatex icra-paper
