#! /bin/sh

if [ x$1 = x ]
then
  echo usage vectorgfx2pdf origfile
  exit 1
else
  if [ ! -f $1 ]
  then
    echo file does not exist
    exit 1
  fi
  if [ x$2 = x ]
  then
    echo no output given. assuming default
    rval=`echo $1 | sed "s/\.[^\.]*$//"`
    rval=$rval.pdf
  else
    rval=$2
  fi
  echo inkscape -f $1 -D -z -d 300 -A $rval
  inkscape -f $1 -D -z -d 300 -A $rval
  echo Created $rval
  exit 0
fi

