all:
	cp /home/felix/ss12/bibtex/Master_Thesis.bib /home/felix/ss12/master_thesis/latex/bibtex
	pdflatex thesis
	bibtex thesis
	pdflatex thesis
	pdflatex thesis
short:
	pdflatex thesis
	pdflatex thesis
